### ISSUE TITLE
Dataset help

### ISSUE THREAD

**Issue by Yhw109** [FlyingFeather/DEA-SQL#3]
Hi, I would like to express my sincere gratitude for opening source your inspiring work. I have been trying to download the dataset from the Spider website and reproduce your results, but unfortunately, I found that the data page on the website is not accessible.
 I was wondering if it would be possible for you to kindly update the Spider dataset on the GitHub repository? That would be extremely helpful for me to continue my research and learning.
 Thank you very much for your time and consideration. I truly appreciate your efforts in supporting the community.

**Comment by downeykking** [comment]
Hello, thanks for attention to our work! We have updated the dataset in README.md, you can download the dataset through new link.
